name = "nsfw-commission-workers"

# pages_build_output_dir = ".vercel/output/static"
# pages_build_output_dir = "out"

# compatibility_flags = ["nodejs_compat"]

compatibility_date = "2025-07-02"

[assets]
directory = "./out"
