export type {
  FilteredSuggestion,
  SearchEntryLike,
  SearchIndexLike,
  Suggestion,
  SuggestionEntryLike,
  SuggestionRows,
  SuggestionSource,
  SuggestionTokenOperator,
} from '@commission-index/domain'
export {
  applySuggestionToQuery,
  buildStrictTermIndex,
  collectSuggestions,
  createSearchFuse,
  createSearchIndex,
  filterSuggestions,
  getMatchedEntryIds,
  hydrateSearchIndexFuse,
  normalizeQuery,
  normalizeQuotedTokenBoundary,
  normalizeSuggestionTerm,
  parseSuggestionInputState,
  parseSuggestionRows,
  resolveSuggestionContextMatchedIds,
} from '@commission-index/domain'
